config/routes.rb
Rails.application.routes.draw do
  get "settings/show"
  scope "(:locale)", locale: /en|es|gr|fr/ do # Will add more locales later
    resources :posts do
      scope module: :posts do
        resources :reactions, only: [:create]
        resources :comments, only: [:new, :create, :index]
      end
    end

    resources :feeds, only: [:show]

    devise_for :users

    resources :users, only: [:show] do
      member do
        post 'follow'
        delete 'unfollow'
      end
    end

    resources :jobs
    get "pages/home", to: "pages#home", as: :pages_home
    get "pages/about", to: "pages#about", as: :pages_about
    get "pages/tos", to: "pages#tos", as: :pages_tos
    get "pages/privacy-policy", to: "pages#privacy_policy", as: :pages_privacy_policy
    get "pages/network", to: "pages#network", as: :network
    get "pages/messages", to: "pages#messages", as: :messages
    get "settings", to: "settings#show", as: :settings

    # Health check route
    get "up" => "rails/health#show", as: :rails_health_check

    # PWA dynamic routes
    get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
    get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

    authenticated :user do
      root to: "feed#show", as: :authenticated_user_root
    end

    # Root path route ("/")
    root "pages#home"
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_rich_text :body
  has_many_attached :images
  has_many :reactions, dependent: :destroy
  has_many :comments, dependent: :destroy

  def feed_body
    char_limit = images.any? ? 100 : 400
    body&.body&.to_plain_text&.first(char_limit)
  end

  def feed_body_is_larger?
    start_chars = body&.body&.to_plain_text&.chars&.count || 0
    feed_chars = feed_body&.chars&.count || 0
    start_chars > feed_chars
  end
end

app/controllers/posts/base_controller.rb
module Posts
  class BaseController < ApplicationController
    before_action :set_post

    private

    def set_post
      @post = Post.find(params[:post_id])
    end
  end
end

app/controllers/posts/comments_controller.rb
module Posts
  class CommentsController < BaseController
    def new; end

    def create
      @comment = @post.comments.new(comment_params)
      @comment.user = current_user

      respond_to do |format|
        if @comment.save
          format.turbo_stream
        else
          # Redirect back with an alert if the comment fails to save
          format.html { redirect_to post_path(@post), alert: "Comment could not be created." }
        end
      end
    end

    def index; end

    private

    def comment_params
      params.require(:comment).permit(:body)
    end
  end
end

app/controllers/posts/reactions_controller.rb
module Posts
  class ReactionsController < BaseController
    def create
      reaction = current_user.reactions.find_or_create_by(post: @post)
      reaction.update(name: params[:name])
      respond_to do |format|
        format.turbo_stream { }
      end
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_current_user_post, only: %i[edit update destroy]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
    @post = Post.find(params[:id])
  end

  # GET /posts/new
  def new
    if current_user
      @post = current_user.posts.new
    else
      redirect_to login_path, alert: "You must be logged in to create a post."
    end
  end

  # POST /posts or /posts.json
  def create
    @post = current_user.posts.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to root_path(locale: I18n.locale), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /posts/1/edit
  def edit
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post, locale: I18n.locale), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url(locale: I18n.default_locale), notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_current_user_post
    @post = current_user.posts.find_by(id: params[:id])
    redirect_to posts_path, alert: "Post not found." if @post.nil?
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:caption, :body, images: [])
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/comments/_comment.html.erb
<div class="rounded-lg bg-gray-200 p-2 flex flex-col gap-2">
    <p class="text-base text-black"><%= comment.body %></p>
    <!-- User information -->
    <div class="flex items-center gap-2">
        <span class="text-sm text-slate-800">Commented by <%= comment.user.username %></span>
        <span class="text-sm text-slate-600"><%= time_ago_in_words comment.created_at %> ago </span>
    </div>
</div>

app/views/posts/comments/create.turbo_stream.erb
<%= turbo_stream.append dom_id(post, :comments) do %>
  <%= render partial: "comments/comment", object: @comment %>
<% end %>

app/views/posts/comments/index.html.erb
<div class="w-full flex flex-col items-center pt-24">
    <div class="max-w-5xl w-full mx-auto">
        <%= turbo_frame_tag @post, :comments do %>
            <div class="flex flex-col gap-2">
            <% if @post.comments.any? %>
                <%= render partial: "comment", collection: @post.comments.order(created_at: :desc) %>
            <% else %>
                <p class="text-center text-xl"> No comments🤨 </p>
            <% end %>
            </div>
            <div class="w-full flex justify-between items-center mt-4">
                <%= link_to "Cancel", "/", class: "border-2 border-black bg-blue-100 bg-opacity-15 text-sm text-red p-2 rounded-lg w-52 text-center hover:scale-105 hover:bg-blue-300 duration-150" %>
                <%= link_to "Comment now", new_post_comment_path(@post, locale: I18n.locale), class: "border-2 border-black bg-blue-100 bg-opacity-15 text-sm text-red p-2 rounded-lg w-52 text-center hover:scale-105 hover:bg-blue-300 duration-150" %>
            </div>
        <% end %>
    </div>
</div>

app/views/posts/comments/new.html.erb
<div class="w-full flex flex-col items-center pt-24">
    <div class="max-w-5xl w-full mx-auto">
        <%= turbo_frame_tag @post, :comments do %>
            <%= form_with model: [@post, @post.comments.new], url: post_comments_path(@post, locale: I18n.locale) do |f| %>
                <div class="flex flex-col w-full">
                    <%= f.text_area :body, class: "w-full rounded-lg", placeholder: "I think..." %>
                </div>
                <div class="w-full flex justify-between items-center mt-4">
                    <%= link_to "Cancel", "/", class: "border-2 border-stone-300 bg-blue-100 bg-opacity-15 text-sm text-red p-2 rounded-lg w-52 text-center hover:scale-105 hover:bg-blue-300 duration-150" %>
                    <%= f.submit "Send", class: "border-2 border-stone-300 bg-blue-100 bg-opacity-15 text-base text-black p-2 rounded-lg w-72 text-center cursor-pointer hover:scale-105 hover:bg-blue-300 duration-150" %>
                </div>
            <% end %>
        <% end %>
    </div>
</div>